#include <iostream>
#include <stdexcept>

int main() {
    throw std::runtime_error("Error occurred");
    return 0;
}